### ISSUE TITLE
Special characters in URL causes wrong change of directory

### ISSUE THREAD

**Issue by jirsbek** [vorg/atom-mac-terminal#1]
Thank you for nice plugin, it's nice and fast. Unfortunately I've got most of the projects under URL with special chars like spaces and diacritics which cause wrong change of directory.

**Comment by vorg** [comment]
@jirsbek Could you give me some example string to test with?

**Comment by jirsbek** [comment]
@vorg Of course. For example my project si at path /Users/jirka/Development/Skvělý projekt/ In terminal have to cd "/Users/jirka/Development/Skvělý projekt/" otherwise Terminal would end with "/Users/jirka/Development/Skvělý: No such file or directory"

**Comment by vorg** [comment]
@jirsbek hopefully fixed in v1.0.4 and  https://github.com/vorg/atom-mac-terminal/commit/2fb82b6ce0aa5b3cbe189e32164de16d4718af11

**Comment by jirsbek** [comment]
@vorg Works like a charm now :thumbsup:
